impac:
  paths:
    mnohub_api: /mnoe/jpi/v1
  pusher:
    key: <%= ENV['impac_pusher_key'] %>
mno:
  paths:
    root: /api/mnoe/v1
frontend_host:
pricing:
  enabled: false
dock:
  enabled: true
developer:
  enabled: true
marketplace:
  enabled: true
admin_panel:
  dashboard_templates:
    enabled: true
